name: e_care_mobile
description: e-care mobile app.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  http: ^0.13.3
  font_awesome_flutter: ^9.1.0
  carbon_icons: ^0.0.1
  dio: ^4.0.0
  shared_preferences: ^2.0.6
  flutter_bloc: ^7.0.1
  freezed: ^0.14.2
  build_runner: ^2.0.5
  build_config: ^1.0.0

  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.4

  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  image_picker: ^0.8.0+3
  page_transition: ^2.0.1-nullsafety.0

  animated_splash_screen: ^1.1.0
  animations: ^2.0.0
  bouncing_widget: ^2.0.0
  flutter_bounce: ^1.1.0
  provider: ^5.0.0
  rxdart: ^0.27.1
  equatable: ^2.0.3
  form_field_validator: ^1.1.0
  delayed_display: ^2.0.0
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  google_sign_in: ^5.0.4
  cloud_firestore: ^2.3.0
  firebase_dynamic_links: ^2.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

 
  assets:
    - assets/images/



  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Thin.ttf
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Light.ttf
          style: normal

